version: "3"

services:
  app-node-liquibase:
    image: crkepler/app-node-liquibase
    container_name: app-node-liquibase
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
      #- ./logs:/app/logs
