version: "3"

services:
  app-node-liquibase:
    image: crkepler/app-node-liquibase
    container_name: app-node-liquibase
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - ./logs:/app/logs
      - ./liquibase:/app/liquibase